name: Katkı Yılanı

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  uret:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Yılan animasyonunu üret
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%231A7F37&color_dots=%23EBEDF0,%239BE9A8,%2340C463,%2330A14E,%23216E39
            dist/github-snake-dark.svg?color_snake=%233FB950&color_dots=%23161B22,%230E4429,%23006D32,%2326A641,%2339D353

      - name: output dalına yayınla
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
